const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT 
global.appUrl=process.env.APP_URL || ""     // put your deploy app/bot url here, for 24/7 for (render , koyeb, glitch)
global.email ="saimsamsun789@gmail.com"
global.location="Lahore,Pakistan."


global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "";
global.gurl  =process.env.GURL  || "";
global.website=process.env.GURL || "" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "" || "" ; // SET LOGO FOR IMAGE 
global.caption = process.env.CAPTION || global.caption || "BLUE DEMON !" 


global.devs = "2347041039367" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "2347041039367,2349164900158";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "2347041039367";




//========================= [ BOT SETTINGS ] ======8===================\\
global.style = process.env.STYLE   || Math.floor(Math.random()*6) || '0'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || process.env.CAN_GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || process.env.CAN_WELCOME || Math.floor(Math.random()*3)  === 1 ?  "false" : "false" ;  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 10
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "" // "text" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "available" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "true"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd.onrender.com" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";


global.SESSION_ID = process.env.SESSION_ID  || "SUHAIL_18_23_10_19_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNzIsXG4gICAgICAgIDE1NyxcbiAgICAgICAgNDgsXG4gICAgICAgIDMyLFxuICAgICAgICAxMjMsXG4gICAgICAgIDEyMixcbiAgICAgICAgNDAsXG4gICAgICAgIDkyLFxuICAgICAgICAxMTgsXG4gICAgICAgIDI1MixcbiAgICAgICAgMjMsXG4gICAgICAgIDQ1LFxuICAgICAgICAxMjcsXG4gICAgICAgIDExMixcbiAgICAgICAgMTQsXG4gICAgICAgIDEyNyxcbiAgICAgICAgMTk4LFxuICAgICAgICAyNDQsXG4gICAgICAgIDEzNCxcbiAgICAgICAgMTI5LFxuICAgICAgICAyMjEsXG4gICAgICAgIDY4LFxuICAgICAgICA3MyxcbiAgICAgICAgMTExLFxuICAgICAgICAyMSxcbiAgICAgICAgMTMzLFxuICAgICAgICAyNDUsXG4gICAgICAgIDIyNCxcbiAgICAgICAgMTEwLFxuICAgICAgICAxODAsXG4gICAgICAgIDE4MyxcbiAgICAgICAgMTI1XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDM1LFxuICAgICAgICA4MixcbiAgICAgICAgMTc1LFxuICAgICAgICA0NyxcbiAgICAgICAgMixcbiAgICAgICAgMjQ4LFxuICAgICAgICA5NixcbiAgICAgICAgNTgsXG4gICAgICAgIDEyLFxuICAgICAgICA3NCxcbiAgICAgICAgMjIyLFxuICAgICAgICAyMTAsXG4gICAgICAgIDM3LFxuICAgICAgICAxNzQsXG4gICAgICAgIDE1NyxcbiAgICAgICAgMTY1LFxuICAgICAgICAyMzUsXG4gICAgICAgIDM0LFxuICAgICAgICAxMzgsXG4gICAgICAgIDE5OCxcbiAgICAgICAgMjI1LFxuICAgICAgICAxMjIsXG4gICAgICAgIDE1NSxcbiAgICAgICAgMjEyLFxuICAgICAgICAyNSxcbiAgICAgICAgMTA5LFxuICAgICAgICAzNyxcbiAgICAgICAgNzcsXG4gICAgICAgIDIzMSxcbiAgICAgICAgNTAsXG4gICAgICAgIDEyMixcbiAgICAgICAgNTdcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwicGFpcmluZ0VwaGVtZXJhbEtleVBhaXJcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDQwLFxuICAgICAgICA1NCxcbiAgICAgICAgNjUsXG4gICAgICAgIDU2LFxuICAgICAgICAxOTYsXG4gICAgICAgIDIzMixcbiAgICAgICAgMjAzLFxuICAgICAgICA3OCxcbiAgICAgICAgMjUsXG4gICAgICAgIDE3MSxcbiAgICAgICAgMTMzLFxuICAgICAgICA2MixcbiAgICAgICAgNDIsXG4gICAgICAgIDIyMixcbiAgICAgICAgMTU4LFxuICAgICAgICAyLFxuICAgICAgICA0MCxcbiAgICAgICAgMTc2LFxuICAgICAgICA4OCxcbiAgICAgICAgMTYzLFxuICAgICAgICAxODksXG4gICAgICAgIDk5LFxuICAgICAgICAxNDYsXG4gICAgICAgIDE3MixcbiAgICAgICAgMTYxLFxuICAgICAgICAyMjYsXG4gICAgICAgIDY2LFxuICAgICAgICAxMTksXG4gICAgICAgIDE2OCxcbiAgICAgICAgMjE1LFxuICAgICAgICAxMTksXG4gICAgICAgIDc5XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDQxLFxuICAgICAgICAxODAsXG4gICAgICAgIDIyNSxcbiAgICAgICAgMjQzLFxuICAgICAgICAyMDYsXG4gICAgICAgIDM3LFxuICAgICAgICAxNjUsXG4gICAgICAgIDI0MSxcbiAgICAgICAgMzYsXG4gICAgICAgIDI1MCxcbiAgICAgICAgMjEyLFxuICAgICAgICAyMjEsXG4gICAgICAgIDI0NSxcbiAgICAgICAgMTIsXG4gICAgICAgIDExMCxcbiAgICAgICAgMjExLFxuICAgICAgICAyNDAsXG4gICAgICAgIDc2LFxuICAgICAgICAyNyxcbiAgICAgICAgMTUsXG4gICAgICAgIDk2LFxuICAgICAgICAxMDksXG4gICAgICAgIDIyMCxcbiAgICAgICAgMjU0LFxuICAgICAgICAyNyxcbiAgICAgICAgMTExLFxuICAgICAgICAxODcsXG4gICAgICAgIDE0MCxcbiAgICAgICAgNTgsXG4gICAgICAgIDI1MCxcbiAgICAgICAgMTI5LFxuICAgICAgICA5XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZElkZW50aXR5S2V5XCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyMDgsXG4gICAgICAgIDM3LFxuICAgICAgICAxMDAsXG4gICAgICAgIDcyLFxuICAgICAgICAxMTUsXG4gICAgICAgIDczLFxuICAgICAgICA2MSxcbiAgICAgICAgODMsXG4gICAgICAgIDI0MCxcbiAgICAgICAgMSxcbiAgICAgICAgMTgxLFxuICAgICAgICAyNDEsXG4gICAgICAgIDEyNSxcbiAgICAgICAgMTYsXG4gICAgICAgIDczLFxuICAgICAgICAxMjYsXG4gICAgICAgIDUxLFxuICAgICAgICA3OSxcbiAgICAgICAgMTE3LFxuICAgICAgICAxMjUsXG4gICAgICAgIDIyMyxcbiAgICAgICAgOTUsXG4gICAgICAgIDQ0LFxuICAgICAgICAyMTksXG4gICAgICAgIDEwOCxcbiAgICAgICAgMTEwLFxuICAgICAgICA1OSxcbiAgICAgICAgMTc5LFxuICAgICAgICAyNDAsXG4gICAgICAgIDE3NixcbiAgICAgICAgNDksXG4gICAgICAgIDEwNFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxNTIsXG4gICAgICAgIDcyLFxuICAgICAgICA0MSxcbiAgICAgICAgMjI4LFxuICAgICAgICAxMjcsXG4gICAgICAgIDgxLFxuICAgICAgICAyMjQsXG4gICAgICAgIDE4MSxcbiAgICAgICAgNjIsXG4gICAgICAgIDI0OSxcbiAgICAgICAgMTI1LFxuICAgICAgICAxOTYsXG4gICAgICAgIDMzLFxuICAgICAgICAxMjUsXG4gICAgICAgIDE4LFxuICAgICAgICAyMzcsXG4gICAgICAgIDUxLFxuICAgICAgICAxMDgsXG4gICAgICAgIDg1LFxuICAgICAgICAxODAsXG4gICAgICAgIDExLFxuICAgICAgICA5NixcbiAgICAgICAgMjA0LFxuICAgICAgICAyNDAsXG4gICAgICAgIDEwOSxcbiAgICAgICAgMjUxLFxuICAgICAgICA3MSxcbiAgICAgICAgOTIsXG4gICAgICAgIDE4NyxcbiAgICAgICAgMTgxLFxuICAgICAgICAxMDcsXG4gICAgICAgIDcwXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDIzMixcbiAgICAgICAgICA2NixcbiAgICAgICAgICAyMzIsXG4gICAgICAgICAgMTA3LFxuICAgICAgICAgIDE0OSxcbiAgICAgICAgICAxODAsXG4gICAgICAgICAgMTM2LFxuICAgICAgICAgIDE0NCxcbiAgICAgICAgICAyMzQsXG4gICAgICAgICAgMjUxLFxuICAgICAgICAgIDE5MCxcbiAgICAgICAgICAyMDMsXG4gICAgICAgICAgMyxcbiAgICAgICAgICAxMCxcbiAgICAgICAgICAyMDMsXG4gICAgICAgICAgMCxcbiAgICAgICAgICAxNzQsXG4gICAgICAgICAgMjMyLFxuICAgICAgICAgIDIwOCxcbiAgICAgICAgICAzLFxuICAgICAgICAgIDI1MixcbiAgICAgICAgICA2NCxcbiAgICAgICAgICAxOSxcbiAgICAgICAgICA0MSxcbiAgICAgICAgICAyMzUsXG4gICAgICAgICAgODksXG4gICAgICAgICAgMTQ0LFxuICAgICAgICAgIDIwMSxcbiAgICAgICAgICAxOTEsXG4gICAgICAgICAgMTU3LFxuICAgICAgICAgIDQwLFxuICAgICAgICAgIDgyXG4gICAgICAgIF1cbiAgICAgIH0sXG4gICAgICBcInB1YmxpY1wiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDE2MixcbiAgICAgICAgICAyMjIsXG4gICAgICAgICAgMTAwLFxuICAgICAgICAgIDE4MCxcbiAgICAgICAgICAxMDUsXG4gICAgICAgICAgMjAsXG4gICAgICAgICAgNjUsXG4gICAgICAgICAgNjUsXG4gICAgICAgICAgMjQ1LFxuICAgICAgICAgIDUsXG4gICAgICAgICAgODcsXG4gICAgICAgICAgMTA0LFxuICAgICAgICAgIDc0LFxuICAgICAgICAgIDM1LFxuICAgICAgICAgIDIxMyxcbiAgICAgICAgICAyMTcsXG4gICAgICAgICAgMzQsXG4gICAgICAgICAgMTQwLFxuICAgICAgICAgIDgxLFxuICAgICAgICAgIDE4NixcbiAgICAgICAgICAxOTUsXG4gICAgICAgICAgMTkwLFxuICAgICAgICAgIDU4LFxuICAgICAgICAgIDE2OSxcbiAgICAgICAgICAyMzYsXG4gICAgICAgICAgMTIxLFxuICAgICAgICAgIDE4OCxcbiAgICAgICAgICAyMDQsXG4gICAgICAgICAgMjQyLFxuICAgICAgICAgIDkyLFxuICAgICAgICAgIDE4LFxuICAgICAgICAgIDRcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyMyxcbiAgICAgICAgMjI5LFxuICAgICAgICAyMDgsXG4gICAgICAgIDY1LFxuICAgICAgICA3MCxcbiAgICAgICAgMTYwLFxuICAgICAgICAyMzEsXG4gICAgICAgIDM2LFxuICAgICAgICAxNDQsXG4gICAgICAgIDE1OCxcbiAgICAgICAgMTUyLFxuICAgICAgICAxMzgsXG4gICAgICAgIDEwNyxcbiAgICAgICAgMTQ0LFxuICAgICAgICA0NSxcbiAgICAgICAgNTEsXG4gICAgICAgIDcxLFxuICAgICAgICAxMzQsXG4gICAgICAgIDIwMSxcbiAgICAgICAgOTgsXG4gICAgICAgIDEyLFxuICAgICAgICAyOCxcbiAgICAgICAgMjM5LFxuICAgICAgICAyMjksXG4gICAgICAgIDE5MSxcbiAgICAgICAgMTQwLFxuICAgICAgICAxMDQsXG4gICAgICAgIDUwLFxuICAgICAgICAyNyxcbiAgICAgICAgMTcsXG4gICAgICAgIDQxLFxuICAgICAgICAxNTIsXG4gICAgICAgIDE2MyxcbiAgICAgICAgMTM0LFxuICAgICAgICAyMTMsXG4gICAgICAgIDM0LFxuICAgICAgICAxMCxcbiAgICAgICAgOTMsXG4gICAgICAgIDIwMixcbiAgICAgICAgNzUsXG4gICAgICAgIDE1NyxcbiAgICAgICAgMTYxLFxuICAgICAgICAyNixcbiAgICAgICAgMTcyLFxuICAgICAgICA5MSxcbiAgICAgICAgMjA3LFxuICAgICAgICA3MixcbiAgICAgICAgMjksXG4gICAgICAgIDIxNixcbiAgICAgICAgODcsXG4gICAgICAgIDE0LFxuICAgICAgICAyNDUsXG4gICAgICAgIDgwLFxuICAgICAgICAyNDUsXG4gICAgICAgIDE0NyxcbiAgICAgICAgMTQ0LFxuICAgICAgICAxNzIsXG4gICAgICAgIDIxLFxuICAgICAgICAxNDIsXG4gICAgICAgIDk5LFxuICAgICAgICAyMTIsXG4gICAgICAgIDMxLFxuICAgICAgICAxNDksXG4gICAgICAgIDEzNVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJrZXlJZFwiOiAxXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uSWRcIjogOTEsXG4gIFwiYWR2U2VjcmV0S2V5XCI6IFwiY3JyRmRqNi9LVTlyS3BsQkxORldvTW9QdEZnOWE5Z2R6NldJem83MTcvYz1cIixcbiAgXCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXNcIjogW1xuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCIyMzQ5MTY0OTAwMTU4QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCIzNjRCM0Q2NzkyNUUxRTBEMDJCODMwNjUxOURGMjgxQlwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjkzNjIyMDhcbiAgICB9LFxuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCIyMzQ5MTY0OTAwMTU4QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCI0MUIwNEY4QUFEODEwQjFENEJCNjYzQjkwMzQ0NUY4OFwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjkzNjIyMDhcbiAgICB9XG4gIF0sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAxLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwiMElscTBsZTFRU3lDTDNGSk54dE1DUVwiLFxuICBcInBob25lSWRcIjogXCIyYzA5M2MwYi1hNzg0LTQ0NmMtYjQ5YS0zMjYyM2ZmZTViMmJcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMTkwLFxuICAgICAgMTA4LFxuICAgICAgMzAsXG4gICAgICAyMzIsXG4gICAgICAxNzcsXG4gICAgICAxOTUsXG4gICAgICAyMDQsXG4gICAgICAxMzgsXG4gICAgICA3MixcbiAgICAgIDg0LFxuICAgICAgNjMsXG4gICAgICAxNDIsXG4gICAgICAyMDYsXG4gICAgICA0NCxcbiAgICAgIDk2LFxuICAgICAgMTAsXG4gICAgICAxOTIsXG4gICAgICA2MyxcbiAgICAgIDQsXG4gICAgICA5M1xuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RlcmVkXCI6IHRydWUsXG4gIFwiYmFja3VwVG9rZW5cIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAxNDYsXG4gICAgICAxMDQsXG4gICAgICA0MyxcbiAgICAgIDY4LFxuICAgICAgOTQsXG4gICAgICAyNTAsXG4gICAgICAxMDIsXG4gICAgICAxODEsXG4gICAgICAxMzMsXG4gICAgICAyNDEsXG4gICAgICAxMDMsXG4gICAgICAyMzYsXG4gICAgICA5NyxcbiAgICAgIDE2MSxcbiAgICAgIDEzMCxcbiAgICAgIDU1LFxuICAgICAgMjUxLFxuICAgICAgMTM5LFxuICAgICAgMjAyLFxuICAgICAgMjRcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcInBhaXJpbmdDb2RlXCI6IFwiRzVaUjZUUlRcIixcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjIzNDkxNjQ5MDAxNTg6N0BzLndoYXRzYXBwLm5ldFwiLFxuICAgIFwibmFtZVwiOiBcIlBhcHB5XCIsXG4gICAgXCJsaWRcIjogXCIyMzk0MDU1MDM4NTgxODo3QGxpZFwiXG4gIH0sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ0tQMW5KVUZFSmJ5ejdnR0dBRWdBQ2dBXCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwieG5jQzI5N0xSMTE4cXFBTzgwb1hkMlBsMmZCMDRWbGtGa3NvVzhDamNGRT1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCJSRFpRRm83S0oxU0lxK3ZWd1ZYV0RYZktVay9Pem5ZUWxRSzI3MlIxcHlUclE5Y2Y1cTVyNXpyV0lORytYOGxqZXdFYkphZWZJRzVmQzUxSVFEK2VEUT09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCJTOEJqNmVlK3hoQUh0Sm9vN1ZpWG1DREdSSUdkZHN5WW83Y2lKNlBvUm1BUlZ6cG5FenE2TWc2MEVBNXV0UWJ2bThDTzNHSjB5YXFRNEV5dFhmQWtqdz09XCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCIyMzQ5MTY0OTAwMTU4OjdAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICAxOTgsXG4gICAgICAgICAgMTE5LFxuICAgICAgICAgIDIsXG4gICAgICAgICAgMjE5LFxuICAgICAgICAgIDIyMixcbiAgICAgICAgICAyMDMsXG4gICAgICAgICAgNzEsXG4gICAgICAgICAgOTMsXG4gICAgICAgICAgMTI0LFxuICAgICAgICAgIDE3MCxcbiAgICAgICAgICAxNjAsXG4gICAgICAgICAgMTQsXG4gICAgICAgICAgMjQzLFxuICAgICAgICAgIDc0LFxuICAgICAgICAgIDIzLFxuICAgICAgICAgIDExOSxcbiAgICAgICAgICA5OSxcbiAgICAgICAgICAyMjksXG4gICAgICAgICAgMjE3LFxuICAgICAgICAgIDI0MCxcbiAgICAgICAgICAxMTYsXG4gICAgICAgICAgMjI1LFxuICAgICAgICAgIDg5LFxuICAgICAgICAgIDEwMCxcbiAgICAgICAgICAyMixcbiAgICAgICAgICA3NSxcbiAgICAgICAgICA0MCxcbiAgICAgICAgICA5MSxcbiAgICAgICAgICAxOTIsXG4gICAgICAgICAgMTYzLFxuICAgICAgICAgIDExMixcbiAgICAgICAgICA4MVxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwic21iYVwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzI5MzYyMjAzLFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBRWRtXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFFZG0uanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJRQW5KRm9lTHYrSWRlRDA0Q3Y3UnBjc0xUdm1VSTY5MEVuU0tOS1Izb3d3PVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjEzODY2OTEyMzUsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMTcyOTM2MjIwNjgzNVwifSIKfQ=="  // PUT your SESSION_ID 


module.exports = {

  menu: process.env.MENU || "3", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.0.1-developement-x",
  caption : global.caption || "💙" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "BLUE DEMON",
  packname: process.env.PACK_NAME || "BLUE DEMON",
  botname : process.env.BOT_NAME  || "BLUE DEMON",
  ownername:process.env.OWNER_NAME|| "BLUE DEMON",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "private",
  LANG: ( process.env.THEME ||  "BLUE DEMON"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
